---
- name: Execute task in pods
  hosts: localhost
  gather_facts: no
  vars:
    cgclients: []
    ddosclients: []

  tasks:
#--------------------------------------Configuration------------------------------------------------------------------------------------
    - name: Include client counts
      include_vars:
        file: clients_number.yaml
  
    - name: Crear cgclients
      set_fact:
        cgclients: "{{ cgclients + [{'name': 'cgclient' ~ item, 'pod': 'cgclient' ~ item}] }}"
      loop: "{{ range(1, cg_count + 1)|list }}"
    
    - name: Crear ddosclients
      set_fact:
        ddosclients: "{{ ddosclients + [{'name': 'ddosclient' ~ item, 'pod': 'ddosclient' ~ item}] }}"
      loop: "{{ range(1, ddos_count + 1)|list }}"
    
    - name: Include server IPs
      include_vars:
        file: "{{ playbook_dir }}/server_ips.yaml"

    - name: Debug loaded server IPs
      debug:
        var: ddosserver_ip

    - name: Debug loaded server IPs
      debug:
        var: cgserver_ip


#-----------------------------TCPDUMPS-------------------------------------------------------------------------------------------------

    - name: Start dumps
      shell: kubectl exec -n ddos {{ item.pod }} -- tcpdump -i {{ item.interface }} -w /home/{{ item.pod }}_{{ item.interface }}.pcap
      loop:
        - { pod: "ceos1", interface: "eth4" }
        - { pod: "ceos1", interface: "eth1" }
        - { pod: "ceos1", interface: "eth2" }
        - { pod: "ceos1", interface: "eth3" }
        - { pod: "ceos1", interface: "eth5" }
        - { pod: "ceos1", interface: "eth6" }
        - { pod: "ceos1", interface: "eth7" }
        - { pod: "ceos1", interface: "eth8" }
        - { pod: "ceos2", interface: "eth4" }
        - { pod: "ceos2", interface: "eth1" }
        - { pod: "ceos2", interface: "eth2" }
        - { pod: "ceos2", interface: "eth3" }
        - { pod: "ceos3", interface: "eth4" }
        - { pod: "ceos3", interface: "eth1" }
        - { pod: "ceos3", interface: "eth2" }
        - { pod: "ceos3", interface: "eth3" }
        - { pod: "ceos4", interface: "eth1" }
        - { pod: "ceos4", interface: "eth2" }
        - { pod: "ceos4", interface: "eth3" }
        - { pod: "ceos4", interface: "eth4" }
        - { pod: "ceos4", interface: "eth5" }
      async: 3600
      poll: 0


#---------------------------------Tasks execution---------------------------------------------------------------------------------------
    # Cglient:
    - name: Execute shorts
      shell: kubectl exec -n ddos cgclient1 -- python3 ACROSSshorts.py 1800
      async: 3600 
      poll: 0
      register: acrossclient_result

    - name: Execute file_transfer
      shell: kubectl exec -n ddos cgclient2 -- python3 ACROSSfile_transfer.py https://ia800301.us.archive.org/21/items/ThePhantomoftheOpera/Phantom_of_the_Opera_512kb.mp4
      async: 3600 
      poll: 0

    - name: Execute file_transfer_scp
      shell: kubectl exec -n ddos cgclient3 -- env cgserver={{ cgserver_ip }} python3 ACROSSfile_transfer_scp.py
      async: 3600 
      poll: 0

    - name: Execute ACROSSrandom_walk
      shell: kubectl exec -n ddos cgclient4 --  python3 ACROSSrandom_walk.py 1800
      async: 3600 
      poll: 0 
      register: acrossclient_result1

    - name: Execute ACROSSrandom_walk
      shell: kubectl exec -n ddos cgclient5 --  python3 ACROSSrandom_walk.py 1800
      async: 3600 
      poll: 0  
      register: acrossclient_result2

    # ddosclient:
    - name: Execute hping
      shell: kubectl exec -n ddos ddosclient1 -- env ddosserver={{ ddosserver_ip }} /bin/bash -c 'sudo hping3 -c 50 -d 100 -S $ddosserver -w 1232 -p 43 --flood'
      async: 3600 
      poll: 0

    - name: Execute doh flood
      shell: kubectl exec -n ddos ddosclient2 -- python3 cne-DoH-master/floodoh.py 30000 www.example.com A https://micaddy.com/dns-query
      async: 3600 
      poll: 0

    - name: Execute quic-flooding.sh
      shell: kubectl exec -n ddos ddosclient3 -- /bin/bash -c './quic-flooding.sh'
      async: 3600 
      poll: 0

    # Waiting tasks
    - name: Waiting
      async_status:
        jid: "{{ item.ansible_job_id }}"
      loop:
        - "{{ acrossclient_result }}"
        - "{{ acrossclient_result1 }}"
        - "{{ acrossclient_result2 }}"
      register: acrossclient_jobs
      until: acrossclient_jobs.finished
      retries: 999
      delay: 15
      ignore_errors: yes

