{
 "title": "ACROSS - TC3.1 Monitoring",
 "tags": [ "ACROSS" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Arista R1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Link Utilization - Inbound [R1]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.13\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R1]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.13\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R1] - 10.244.1.13",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.86\"}[1m]) * 8  / 60 / 1e6,2)",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R1] - 10.244.1.13",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.13\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R1]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "round(increase(ifInDiscards{instance=\"10.244.1.13\"}[1m]) / 60, 2)",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R1]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.13\"}[1m]) / 60, 2)\r\n",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  { "title": "Arista R2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Link Utilization - Inbound [R2]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.9\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R2]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.9\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R2] - 10.244.1.9",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.9\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R2] - 10.244.1.9",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.9\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R2] - 10.244.1.101",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "round(increase(ifInDiscards{instance=\"10.244.1.9\"}[1m]) / 60, 2)",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R2]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.9\"}[1m]) / 60, 2)\r\n",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Arista R3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R3]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.11\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R3]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.11\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R3] - 10.244.1.11",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.11\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R3] - 10.244.1.11",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.11\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R3]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 321 },
     "targets": [
      {
       "expr": "round(increase(ifInDiscards{instance=\"10.244.1.11\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R3]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 321 },
     "targets": [
      {
       "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.11\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R4]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 389 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.247\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R4]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 389 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.247\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R4] - 10.244.1.247",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 517 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.247\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R4] - 10.244.1.247",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 517 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.247\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R4]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 528 },
     "targets": [
      {
       "expr": "round(increase(ifInDiscards{instance=\"10.244.1.247\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R4]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 528 },
     "targets": [
      {
       "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.247\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    }
   ]
  },
  { "title": "Arista R5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Link Utilization - Inbound [R5]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.10\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R5]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.10\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R5] - 10.244.1.10",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.10\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R5] - 10.244.1.10",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.10\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R5]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "round(increase(ifInDiscards{instance=\"10.244.1.10\"}[1m]) / 60, 2)",
     "legendFormat": "{{ifName}} In"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R5]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 78 },
   "targets": [
    {
     "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.10\"}[1m]) / 60, 2)\r\n",
     "legendFormat": "{{ifName}} Out"
    }
   ]
  },
  {
   "title": "Arista R6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R6]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.239\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R6]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.239\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R6] - 10.244.1.239",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 459 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.239\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R6] - 10.244.1.239",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 459 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.239\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R6]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 472 },
     "targets": [
      {
       "expr": "round(increase(ifInDiscards{instance=\"10.244.1.239\"}[1m]) / 60, 2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R6]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 472 },
     "targets": [
      {
       "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.239\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R7",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R7]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.14\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R7]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.14\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R7] - 10.244.1.14",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 429 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.14\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R7] - 10.244.1.14",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 429 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.14\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R7]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 441 },
     "targets": [
      {
       "expr": "round(increase(ifInDiscards{instance=\"10.244.1.14\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R7]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 441 },
     "targets": [
      {
       "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.14\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R8",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R8]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 393 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.12\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R8]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 393 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.12\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R8] - 10.244.1.12",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 399 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.12\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R8] - 10.244.1.12",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 399 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.12\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R8]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 412 },
     "targets": [
      {
       "expr": "round(increase(ifInDiscards{instance=\"10.244.1.12\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R8]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 412 },
     "targets": [
      {
       "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.12\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R9",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R9]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 311 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.8\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R9]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 311 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.8\"}[1m]) * 8  / 60 / 1e6, 2)\r\n",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R9] - 10.244.1.8",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 317 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifInOctets{instance=\"10.244.1.8\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R9] -  10.244.1.8",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 317 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "round(increase(ifOutOctets{instance=\"10.244.1.8\"}[1m]) * 8 / 60 / 1e6,2)",
       "legendFormat": "{{ifName}} Out"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R9]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 329 },
     "targets": [
      {
       "expr": "round(increase(ifInDiscards{instance=\"10.244.1.8\"}[1m]) / 60, 2)",
       "legendFormat": "{{ifName}} In"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R9]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 329 },
     "targets": [
      {
       "expr": "round(increase(ifOutDiscards{instance=\"10.244.1.8\"}[1m]) / 60, 2)\r\n",
       "legendFormat": "{ifName}} Out"
      }
     ]
    }
   ]
  }
 ]
}