# iperf3.conf
# IPs asociadas a los enlaces de routers
LINKS_TO_MEASURE=("R4" "R10")   # Identificadores de los enlaces a medir

# Configuración de iperf3
PROTOCOL="-u"
BANDWIDTH="-b 1M"
DURATION="-t 10"

POOLING="60"  # Intervalo de tiempo en segundos para ejecutar las mediciones
