# iperf3.conf
# IPs asociadas a los enlaces de routers
LINKS_TO_MEASURE=("R2" "R9")   # Identificadores de los enlaces a medir
IPERF_PORT="5201"

# Configuración de iperf3
PROTOCOL="-u"
BANDWIDTH="-b 10M"
DURATION="-t 10"

POOLING="20"  # Intervalo de tiempo en segundos para ejecutar las mediciones
