{
 "title": "ACROSS - TC3.4 Monitoring",
 "tags": [ "ACROSS" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Network Digital Twin - ACROSS",
   "type": "knightss27-weathermap-panel",
   "gridPos": { "h": 19, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": " R1_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": " R1_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R2_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R2_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R3_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R4_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R5_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R6_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R7_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R8_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R9_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R3_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R4_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R5_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R6_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R7_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R8_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R9_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "ML Prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 19 },
   "targets": [
    { "expr": "ml_tc34_prediction\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet loss (%) [R1-R5][End-to-End]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "iperf3_received_lost_percent{instance=\"10.0.15.10\", job=\"iperf3-probe1\", port=\"5201\", target=\"10.0.15.10\"}",
     "legendFormat": "iperf3_job server"
    }
   ]
  },
  {
   "title": "Jitter (ms) [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "\r\niperf3_received_jitter_ms{instance=\"10.0.15.10\", job=\"iperf3-probe1\", port=\"5201\", target=\"10.0.15.10\"}",
     "legendFormat": "iperf3_job server"
    }
   ]
  },
  {
   "title": "Probe Duration [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_probe1\", instance=\"10.1.3.10\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TTL [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 37 },
   "targets": [
    {
     "expr": "probe_icmp_reply_hop_limit{job=\"blackbox_probe1\", instance=\"10.1.3.10\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resolve [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"resolve\", job=\"blackbox_probe1\", instance=\"10.1.3.10\"}*1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link availability  [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_probe1\", instance=\"10.1.3.10\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", job=\"blackbox_probe1\", instance=\"10.1.3.10\"}* 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Flow from R1 (eth4) [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.86\", ifName=\"Ethernet4\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "Iperf3 Server"
    }
   ]
  },
  {
   "title": "Input Flow to R5 (Eth4)[R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.87\", ifName=\"Ethernet4\"}[1m]) * 8 / 60 / 1e6, 2)",
     "legendFormat": "Iperf3 Client"
    }
   ]
  },
  {
   "title": "Output Flow from R1 (eth5) [R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifOutOctets{instance=\"10.244.1.86\", ifName=\"Ethernet5\"}[1m]) * 8 / 60 / 1e6,2)",
     "legendFormat": "Iperf3 Server"
    }
   ]
  },
  {
   "title": "Input Flow to R5 (eth3)[R1-R5][End-to-End]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "round(increase(ifInOctets{instance=\"10.244.1.87\", ifName=\"Ethernet3\"}[1m]) * 8 / 60 / 1e6, 2)",
     "legendFormat": "Iperf3 Client"
    }
   ]
  }
 ]
}