{
 "title": "ACROSS - TC3.1 Monitoring (InfluxDB)",
 "tags": [ "ACROSS" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Network Digital Twin - ACROSS",
   "type": "knightss27-weathermap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": " R1_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": " R1_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R2_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R2_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R3_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R4_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R5_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R6_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R7_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R8_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)"
    },
    {
     "alias": "R9_in + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R3_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R4_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R5_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R6_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R7_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R8_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    },
    {
     "alias": "R9_out + $tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "ML Prediction",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 17 },
   "targets": [
    { "expr": "ml_tc31_prediction\r\n", "legendFormat": "{{label_name}}" }
   ]
  },
  { "title": "Arista R1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Link Utilization - Inbound [R1]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R1]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R1] - 10.244.1.86",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R1] - 10.244.1.86",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R1]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "$tag_ifName in",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R1]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "alias": "$tag_ifName out",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.86/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  { "title": "Arista R2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Link Utilization - Inbound [R2]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R2]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R2] - 10.244.1.91",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R2] - 10.244.1.91",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R2]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "alias": "$tag_ifName in",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R2]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "alias": "$tag_ifName out",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.91/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Arista R3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R3]",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2841 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R3]",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2841 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R3] - 10.244.1.84",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 3520 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R3] - 10.244.1.84",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 3520 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R3]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3533 },
     "targets": [
      {
       "alias": "$tag_ifName in",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R3]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3533 },
     "targets": [
      {
       "alias": "$tag_ifName out",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.84/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    }
   ]
  },
  { "title": "Arista R4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Link Utilization - Inbound [R4]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R4]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R4] - 10.244.1.92",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R4] - 10.244.1.92",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R4]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 116 },
   "targets": [
    {
     "alias": "$tag_ifName in",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R4]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 116 },
   "targets": [
    {
     "alias": "$tag_ifName out",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.92/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Arista R5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R5]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2843 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R5]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2843 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R5] - 10.244.1.87",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 3139 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R5] - 10.244.1.87",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 3139 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R5]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3152 },
     "targets": [
      {
       "alias": "$tag_ifName in",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R5]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3152 },
     "targets": [
      {
       "alias": "$tag_ifName out",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.87/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R6]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1300 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R6]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1300 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R6] - 10.244.1.89",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 1308 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R6] - 10.244.1.89",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 1308 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R6]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1321 },
     "targets": [
      {
       "alias": "$tag_ifName in",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R6]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1321 },
     "targets": [
      {
       "alias": "$tag_ifName out",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.89/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R9",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R9]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1585 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R9]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1585 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R9] - 10.244.1.85",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 1593 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R9] - 10.244.1.85",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 1593 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R9]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1606 },
     "targets": [
      {
       "alias": "$tag_ifName in",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R9]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1606 },
     "targets": [
      {
       "alias": "$tag_ifName out",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.85/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista R7",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Utilization - Inbound [R7]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2942 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Link Utilization - Outbound [R7]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2942 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Inbound Traffic - [R7] - 10.244.1.90",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 2982 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Outbound Traffic - [R7] - 10.244.1.90",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 2982 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_ifName",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ AND \"ifName\" =~ /Ethernet(2|3|4|5)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Ingress Packet Discards [R7]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2995 },
     "targets": [
      {
       "alias": "$tag_ifName in",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    },
    {
     "title": "Egress Packet Discards [R7]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2995 },
     "targets": [
      {
       "alias": "$tag_ifName out",
       "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.90/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
      }
     ]
    }
   ]
  },
  { "title": "Arista R8", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Link Utilization - Inbound [R8]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 \nAS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ \nAND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ \nAND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Link Utilization - Outbound [R8]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Inbound Traffic - [R8] - 10.244.1.83",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifInOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Outbound Traffic - [R8] - 10.244.1.83",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) * 8 / 10 / 1000000 AS \"Ethernet_traffic\"\nFROM \"ifOutOctets\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ AND \"ifName\" =~ /Ethernet(2|3|4|5|6)/ AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Ingress Packet Discards [R8]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 153 },
   "targets": [
    {
     "alias": "$tag_ifName in",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifInDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Egress Packet Discards [R8]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 153 },
   "targets": [
    {
     "alias": "$tag_ifName out",
     "query": "SELECT non_negative_derivative(mean(\"counter\"), 10s) AS \"Discarded_Packets\"\nFROM \"ifOutDiscards\"\nWHERE \"url\" =~ /target=10\\.244\\.1\\.83/ \n  AND \"ifName\" =~ /Ethernet(2|3|4|5)/ \n  AND $timeFilter\nGROUP BY time(10s), \"ifName\" fill(null)\n"
    }
   ]
  }
 ]
}