apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 60s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'iperf3'
        metrics_path: /probe
        static_configs:
          - targets:
            - 10.1.3.10
        params:
          port: ['5201']
          # Optional: enable reverse mode
          # reverse_mode: ['true']
          # Optional: enable UDP mode
          udp_mode: ['true']
          # Optional: set bitrate limit
          bitrate: ['60M']
          # Optional: set test period
          period: ['60s']
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 138.4.21.168:9579  # The iPerf3 exporter's real hostname:port.

      - job_name: 'snmp'
        static_configs:
          - targets:
              - 10.244.1.65 # R1
              - 10.244.1.64 # R2
              - 10.244.1.62  # R3
              - 10.244.1.39  # R4
              - 10.244.1.66 # R5
              - 10.244.1.28  # R6
              - 10.244.1.63  # R7
              - 10.244.1.52  # R8
              - 10.244.1.44  # R9

        metrics_path: /snmp
        params:
          module: [if_mib]
          auth: [public_v1]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 138.4.21.168:9116
